#spring datasouce 和mvc 相关配置
spring: 
  datasource:
#    url: jdbc:mysql://bdm257613210.my3w.com:3306/bdm257613210_db?characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: bdm257613210
#    password: yuanenguang
    url: jdbc:mysql://127.0.0.1:3306/xiaomi?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
 
logging: 
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
  file: D:/log/spring-boot/app.log
#server:
#  port: 80


  
    